name = "wa-templates-worker"
main = "index.js"
compatibility_date = "2024-01-01"

# Existing KV Namespace from previous WhatsApp project
[[kv_namespaces]]
binding = "WA_TEMPLATES_KV"
id = "38a369eeb9824454a91f49c535dd9e42"
